

spring:
#  jpa:
#    properties:
#      hibernate:
#        format_sql=true
#    show-sql: true

  mvc:

    throw-exception-if-no-handler-found: true


  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: komunist
    url: jdbc:postgresql://127.0.0.1:5432/postgres

  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


okta:
  oauth2:
    issuer: https://dev-lxs2cvzdocbe1ne6.eu.auth0.com/
    audience: https://miloverada-api

server:
  port: 8443

  ssl:
    key-store: /etc/letsencrypt/live/v2.miloverada.gov.ua/keystore.p12
    key-store-password: komunist
    key-store-type: PKCS12
    key-alias: tomcat

  error:
    whitelabel:
      enabled: false
    include-message: always

security:
  require-ssl: true

#logging:
#  level:
#    web: debug
