spring:
  config:
    import: "optional:application-prod-environment.properties"

  flyway:
    user: ${postgres_username}
    password: ${postgres_password}
    schemas: public
    url: ${postgres_url}
    baseline-on-migrate: true
    baseline-version: 3

  data:
    mongodb:
      database: ${mongo.database}
      uri: ${mongo_url}
      repositories:
        type: auto
    jpa:

      repositories:
        enabled: true
  jpa:
    properties:
      hibernate:

    show-sql: true
  #    open-in-view: false

  mvc:
    throw-exception-if-no-handler-found: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${postgres_username}
    password: ${postgres_password}
    url: ${postgres_url}

  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

okta:
  oauth2:
    issuer: https://dev-i1ehhh4j3rf2tyqz.us.auth0.com/
    audience: https://miloverada-api

server:
  port: ${port}

  tomcat:
    max-http-form-post-size: 50000000
  ssl:
    enabled: ${ssl.enabled}
    key-store: ${ssl.key.storage_path}
    key-store-password: ${ssl.key.password}
    key-store-type: PKCS12
    key-alias: tomcat

logging:
  file:
    path: logs
    