# Spring MongoDB Configuration
spring.data.mongodb.database=test
spring.data.mongodb.uri=${MONGO_DB_URL}
spring.data.mongodb.repositories.type=auto

  # JPA Configuration
spring.data.jpa.repositories.enabled=true
spring.jpa.show-sql=true
  # spring.jpa.open-in-view=false

  # Spring MVC Configuration
spring.mvc.throw-exception-if-no-handler-found=true

  # DataSource Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_DB_USER}
spring.datasource.password=${POSTGRES_DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/milove

  # Web Resources Configuration
spring.web.resources.add-mappings=false

  # Servlet Multipart Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

  # Devtools Configuration
spring.devtools.livereload.enabled=false
spring.devtools.restart.enabled=false

  # Okta OAuth2 Configuration
okta.oauth2.issuer=https://dev-i1ehhh4j3rf2tyqz.us.auth0.com/
okta.oauth2.audience=https://miloverada-api

  # Server Configuration
server.port=8443
server.tomcat.max-http-form-post-size=50000000

  # SSL Configuration
server.ssl.enabled=true
server.ssl.key-store=/etc/letsencrypt/live/api.miloverada.gov.ua/keystore.p12
server.ssl.key-store-password=${SSL_KEY_STORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat

  # Logging Configuration
logging.file.path=logs
